[package]
name = "smarthome-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.17", features = ["derive"] }
rustyline = "10.0.0"
rustyline-derive = "0.7.0"
tokio = { version = "1.21.1", features = ["full"] }
serde = "1.0.144"
toml = "0.5.9"
log = "0.4.17"
reqwest = { version = "0.11.11", default-features = false }
smarthome-sdk-rs = {path = '../sdk-rs/'}
tabled = { version = "0.8.0", features = ["color", "derive"] }
loggerv = "0.7.2"
